# Generated by Django 3.2.20 on 2023-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='part',
            name='name_rus',
            field=models.CharField(default='NULL', max_length=255),
            preserve_default=False,
        ),
    ]
