# Generated by Django 3.2.20 on 2023-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230926_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name_eng',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name_rus',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
