# Generated by Django 3.2.20 on 2023-09-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230926_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part',
            field=models.ForeignKey(default='other', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.part'),
        ),
    ]
