# Generated by Django 3.2.20 on 2023-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_word_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.part'),
        ),
    ]
