# Generated by Django 3.2.20 on 2023-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_word_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['rating']},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='name_eng',
            new_name='eng',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='name_rus',
            new_name='rus',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='word',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
